name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v1
    
    - name: Cache
      id: cache
      uses: actions/cache@v1
      with:
        path: katalon-7.2.2
        key: katalon-7.2.2
      
    - name: Download Katalon Studio
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        dir
        certutil.exe -urlcache -split -f "https://github.com/katalon-studio/katalon-studio/releases/download/v7.2.2/lastest_release.json" release.json
        dir
