name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v1
    
#     - name: Cache
#       id: cache
#       uses: actions/cache@v1
#       with:
#         path: katalon
#         key: katalon-7.2.2
      
    - name: Download Katalon Studio
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest -Uri "https://download.katalon.com/7.2.1/Katalon_Studio_Windows_64-7.2.1.zip" -OutFile "katalon.zip"
        dir
