name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v1
    
    - name: Cache
      id: cache
      uses: actions/cache@v1
      with:
        path: katalon-studio
        key: katalon-studio-7.2.1.0
      
    - name: Download Katalon Studio
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        mkdir katalon-studio
        cd katalon-studio
        Invoke-WebRequest -Uri "$Env:DOWNLOAD_LINK" -OutFile "katalon.zip"
        unzip katalon.zip
        rm katalon.zip
      env:
        DOWNLOAD_LINK: https://download.katalon.com/7.2.1/Katalon_Studio_Engine_Windows_64-7.2.1.zip
        
    - name: Download Katalon Studio which need test
      run: |
        Invoke-WebRequest -Uri "$Env:DOWNLOAD_LINK" -OutFile "katalon.zip"
        unzip katalon.zip
        rm katalon.zip
        cd Katalon_Studio_Windows_64-7.2.1
        dir
#       env:
#         DOWNLOAD_LINK: https://download.katalon.com/7.2.1/Katalon_Studio_Engine_Windows_64-7.2.1.zip
        
    - name: Run test
      run: | 
        start /d "C:\Program Files (x86)\Windows Application Driver" WinAppDriver.exe 4723
        set appPath=%cd%\Katalon_Studio_Windows_64-7.2.1\katalon.exe
        set projectPath=%cd%\katalon-window-test.prj
        cd katalon-studio\Katalon_Studio_Engine_Windows_64-7.2.1
        katalonc -noSplash -runMode=console -projectPath="%projectPath%" -retry=0 -testSuitePath="Test Suites/Manage Test Cases/All Cases" -executionProfile="ci_env" -browserType="Windows" -apiKey="478f4186-56e2-497d-9238-ea8870c7d8e1" -g_G_appPath="%appPath%"
      shell: cmd
        
